/*******************************************************************************
 * Copyright © 2015, Province of British Columbia.                             *
 *                                                                             *
 * All rights reserved.                                                        *
 *                                                                             *
 * File:                        FmdbwarSuite.java                              *
 * Date of Last Commit: $Date::                                              $ *
 * Revision Number:      $Rev::                                              $ *
 * Last Commit by:    $Author::                                              $ *
 *                                                                             *
 *******************************************************************************/


package fmdbwar;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */



import junit.framework.*;

/**
 *
 * @author Chris.Prince rip
 */
public class FmdbwarSuite extends junit.framework.TestSuite {

    public FmdbwarSuite(String testName) {
        super(testName);
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("GiswarSuite");

        suite.addTestSuite(LoginTest.class);

        //  suite.addTest(AppPagesSuite.suite());

        return suite;
    }


}

