CREATE SCHEMA IF NOT EXISTS fmdb AUTHORIZATION "fmdb_owner";

GRANT ALL ON SCHEMA fmdb TO "fmdb_owner";

GRANT USAGE ON SCHEMA fmdb TO fmdb_owner;
GRANT USAGE ON SCHEMA fmdb TO fmdb_proxy_user ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA fmdb TO fmdb_proxy_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA fmdb TO fmdb_proxy_user;
GRANT CONNECT ON DATABASE fmdb_db TO fmdb_proxy_user;
