name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      version:
        description: 'Version Number'
        type: string 
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Revert to Tag
        run: |
          git fetch --tags
          git checkout -b Ravi-Rollbackchanges
          git revert -n $(git rev-list -n 1 tags/${{ github.event.inputs.tag }})

      - name: Commit Revert
        run: |
          git commit -am "Revert to tag ${{ github.event.inputs.tag }}"

      - name: Push Revert
        run: |
          git push origin Ravi-Rollbackchanges