name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      version:
        description: 'Version Number'
        type: string 
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Rollback Release
        run: |
          git fetch --tags
          git checkout tags/${{ github.event.inputs.version }}
          # Perform rollback steps specific to your repository

      - name: Revert Changes to Main
        run: |
          git checkout main
          git revert -n ${{ github.event.inputs.version }}
          git commit -m "Revert changes from tag ${{ github.event.inputs.version }}"
          git push origin main       