name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      version:
        description: 'Version Number'
        type: string 
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Rollback Release
        run: |
          git fetch --tags
          git checkout tags/${{ github.event.inputs.version }}
          # Perform rollback steps specific to your repository
      - name: Push Rollback Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git reset --hard ${{ github.event.inputs.version }}
          git push -f origin Ravi-Rollbackchanges

      - name: Update Branch Reference
        run: |
          git symbolic-ref HEAD refs/heads/Ravi-Rollbackchanges
          git push -f origin HEAD:Ravi-Rollbackchanges