name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      version:
        description: 'Version Number'
        type: string 
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Rollback Release
        run: |
          git checkout ${{ github.event.inputs.version }}
          # Perform rollback steps specific to your repository

      - name: Push Rollback Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Rollback changes"
          git push