name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      version:
        description: 'Version Number'
        type: string 
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Rollback Release
        run: |
          git fetch --tags
          git reset --hard tags/${{ github.event.inputs.version }}
          # Perform rollback steps specific to your repository

      - name: Push Rollback Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push -f origin HEAD
